[package]
name = "mintage"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1"
bitflags = "2"
ron = "0.11"
serde = { version = "1", features = ["derive"] }
macroquad = "0.4"
serde_json = "1"
arc-swap = "1"
rayon = "1"
rand = "0.9"
rand_xoshiro = "0.7.0"
image = "0.25.9"